//Global Action Type
export const AUTH_SIGNUP_REQUEST = "AUTH_SIGNUP_REQUEST";
export const AUTH_SIGNUP_SUCCESS = "AUTH_SIGNUP_SUCCESS";
export const AUTH_SIGNUP_FAILURE = "AUTH_SIGNUP_FAILURE";

export const AUTH_LOGIN_REQUEST = "AUTH_LOGIN_REQUEST";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

export const AUTH_ME_REQUEST = "AUTH_ME_REQUEST";
export const AUTH_ME_SUCCESS = "AUTH_ME_SUCCESS";
export const AUTH_ME_FAILURE = "AUTH_ME_FAILURE";

export const AUTH_LOOUT_REQUEST = "AUTH_LOOUT_REQUEST";
export const AUTH_LOOUT_SUCCESS = "AUTH_LOOUT_SUCCESS";
export const AUTH_LOOUT_FAILURE = "AUTH_LOOUT_FAILURE";

export const LAYOUT_SIDEBAR_TOGGLE = "LAYOUT_SIDEBAR_TOGGLE";

// Add Tax

export const CREATE_TAX_REQUEST = "CREATE_TAX_REQUEST";
export const CREATE_TAX_SUCCESS = "CREATE_TAX_SUCCESS";
export const CREATE_TAX_FAILURE = "CREATE_TAX_FAILURE";

export const TAX_LIST_REQUEST = "TAX_LIST_REQUEST";
export const TAX_LIST_SUCCESS = "TAX_LIST_SUCCESS";
export const TAX_LIST_FAILURE = "TAX_LIST_FAILURE";

export const GET_TAX_REQUEST = "GET_TAX_REQUEST";
export const GET_TAX_SUCCESS = "GET_TAX_SUCCESS";
export const GET_TAX_FAILURE = "GET_TAX_FAILURE";

export const DELETE_TAXESS_REQUEST = "DELETE_TAXESS_REQUEST";
export const DELETE_TAXESS_SUCCESS = "DELETE_TAXESS_SUCCESS";
export const DELETE_TAXESS_FAILURE = "DELETE_TAXESS_FAILURE";
