//Global Action Type
export const AUTH_SIGNUP_REQUEST = "AUTH_SIGNUP_REQUEST";
export const AUTH_SIGNUP_SUCCESS = "AUTH_SIGNUP_SUCCESS";
export const AUTH_SIGNUP_FAILURE = "AUTH_SIGNUP_FAILURE";

export const AUTH_LOGIN_REQUEST = "AUTH_LOGIN_REQUEST";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

export const AUTH_ME_REQUEST = "AUTH_ME_REQUEST";
export const AUTH_ME_SUCCESS = "AUTH_ME_SUCCESS";
export const AUTH_ME_FAILURE = "AUTH_ME_FAILURE";

export const AUTH_LOOUT_REQUEST = "AUTH_LOOUT_REQUEST";
export const AUTH_LOOUT_SUCCESS = "AUTH_LOOUT_SUCCESS";
export const AUTH_LOOUT_FAILURE = "AUTH_LOOUT_FAILURE";

export const LAYOUT_SIDEBAR_TOGGLE = 'LAYOUT_SIDEBAR_TOGGLE';
